/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "☰ Player": "☰ 玩家",
    "Challenge": "挑战",
    "Continue": "继续",
    "Core": "核心",
    "Defense": "防御",
    "Gallery": "相册",
    "HP": "生命值",
    "Rewards": "奖励",
    "Skip": "跳过",
    "The Universe is a story being written by the Artist, but you are the Rejected Draft. You refused to be thrown in the trash and are now climbing out of the wastebasket to fight the other sketches and prove your worth.": "这个宇宙是由艺术家所创作的一部故事，而你则是被遗弃的草稿。你拒绝被丢弃在垃圾桶里，如今正从垃圾桶中爬出来，与其他草稿较量，以证明自己的价值。",
    "Utility": "效用",
    "View Journey": "查看旅途",
    "Rejected Draft": "被遗弃的草稿",
    "Rarity": "稀有度",
    "Offense": "进攻",
    "NEW": "新",
    "Anxiety with legs.": "长着腿的焦虑。",
    "Art is pain. Inflict it and reclaim your glory.": "艺术即痛苦。施加痛苦，重夺你的荣光。",
    "Current Specs": "当前属性",
    "Death Recovery": "死亡恢复",
    "Decay Factor": "衰减系数",
    "Economy": "经济机制",
    "Euclid is crying.": "欧几里得在哭泣。",
    "Flee Penalty": "逃跑惩罚",
    "Fundamentals": "基础属性",
    "Glossary Mult": "词条乘数",
    "The Premise": "核心设定",
    "Wax": "蜡质",
    "You missed a spot.": "你漏了一处地方。",
    "Dark": "深色",
    "Void": "虚空",
    "Normal": "正常",
    "Select": "选择",
    "Contrast": "对比度",
    "Dark Mode Only - Can be toggled in Settings.": "仅深色模式 - 可在设置中切换",
    "High contrast. Glowing lines. Digital dreams.": "高对比度，发光线条，数字梦境",
    "How should images appear?": "图片应如何显示？",
    "Inverted": "反色",
    "Original": "原始",
    "Pristine": "纯净",
    "Pure": "纯粹",
    "Select Inverted": "选择反色",
    "Select Original": "选择原始",
    "Select your preferred theme": "选择你偏好的主题",
    "The Artist's light. Blinding. Honest.": "画师之光，耀眼而真实",
    "The Artist's raw ink. Paper and graphite.": "画师原生墨色，纸张与石墨",
    "The wastebasket's comfort. Cool. Quiet.": "废纸篓的慰藉，清冷而安静",
    "This can be changed in settings at any point": "此项可随时在设置中更改",
    "Your Progression": "你的进度",
    "Tutorial:": "教程:",
    "Skip Tutorial": "跳过教程",
    "Previous": "上一条",
    "Next": "下一条",
    "The Gallery": "相册",
    "Each sketch grants specific Stat and Currency rewards upon victory! Click Challenge to enter battle. Combat runs in the background, allowing you to freely navigate to other tabs. Rewards diminish with each repeated victory, so find other victims!": "每场战斗结束后，您都将获得特定的属性和货币奖励！点击“挑战”即可开始战斗。战斗过程在后台进行，您可以自由切换至其他页面。每次获胜后奖励都会减少，所以别放弃寻找其他目标吧！",
    "This sidebar tracks your growth. It displays your current draft, Battle Stats, and Fundamentals. Defeating enemies will improve these stats! Hover over stats and fundamentals to get more information about what they do.": "此侧边栏会记录您的成长情况。它会显示您的当前草稿、战斗统计数据以及基础信息。击败敌人会提升这些数据！将鼠标悬停在数据和基础信息上，即可获取更多关于它们作用的详细信息。",
    "(Tutorial can be reset from Settings)": "（教程可从“设置”中进行重置）",
    "Attack Damage\nBaseline damage dealt per attack before multipliers, variance, and damage reduction.": "攻击伤害\n在乘数，变异和伤害减少之前，每次攻击造成的基线伤害。",
    "Hit Points\nMaximum health. Combat ends immediately when current health reaches zero.": "生命值\n最大生命值。当当前生命值降为零时战斗立即结束。",
    "Welcome to Rejected Draft! The top bar tracks your core currencies. You are currently on the Gallery screen. As you navigate to other tabs like the Shop or Archive, new tutorials will trigger to explain them.": "欢迎来到被拒绝的选秀！顶部栏显示您的核心货币。您当前处于画廊界面。当您切换到其他选项卡（如商店或档案）时，会触发新的教程来解释它们。",
    "The Challenge": "挑战",
    "Attack Speed (Unaffected by Decay Factor)\nDelay between attacks in milliseconds. Lower is faster. Improved by SPD rewards (negative values).": "攻击速度（不受衰减系数影响）\n攻击之间的延迟时间（以毫秒为单位）。延迟时间越短，速度越快。通过 SPD 奖励会有所提升（负值表示）。",
    "Maximum Damage\nThe upper ceiling of damage variance. Base value is 125%. Higher values increase peak damage potential.": "最大伤害\n伤害波动的上限值。基础值为 125%。数值越高，峰值伤害潜力越大。",
    "Minimum Damage\nThe lower floor of damage variance. Base value is 75%. Higher values increase damage consistency.": "最小伤害\n伤害波动的下限值。基础值为 75%。数值越高，伤害的一致性越好。",
    "Close [X]": "关闭 [X]",
    "Your Journey": "你的旅途",
    "Locked": "未解锁",
    "Progress further to reveal this part of your journey.": "继续深入探索，以揭示你旅程中的这一部分。",
    "The painter was hospitalized. Doctors say he had too many strokes.": "这位画家住院了。医生表示他出现了多次中风。",
    "Copy String": "复制存档",
    "CRITIQUE": "评论",
    "FACT": "事实",
    "Join Discord": "加入 Discord",
    "JOKE": "笑话",
    "Load": "加载",
    "Never": "从不",
    "Load String": "加载存档",
    "SHOP ERROR": "商店错误",
    "SHOP AFFORDABLE": "平价商店",
    "Add Dev Tools": "添加开发者工具",
    "⤢ Enter Fullscreen": "⤢ 进入全屏",
    "Save File": "存档文件",
    "Save file downloaded!": "存档文件已下载!",
    "Save string copied to clipboard!": "存档已复制到剪贴板!",
    "Scroll Speed": "滚动速度",
    "Reset Tutorials": "重置教程",
    "Scrolling Tips": "滚动提示",
    "Select File": "选择文件",
    "Show Attack Delays": "显示攻击延迟",
    "Tip Frequency": "提示频率",
    "Always Switch (Even Auto-Challenge)": "自动切换（即使是自动挑战）",
    "Auto Show Redraw Summary": "自动显示重绘摘要",
    "Automatically display run stats after a Redraw.": "重绘后自动显示本局统计",
    "Battle Tab Navigation": "战斗标签页导航",
    "Categories": "分类",
    "COMBAT DEFEAT": "战斗失败",
    "COMBAT FLEE": "战斗逃跑",
    "COMBAT VICTORY": "战斗胜利",
    "Community & Feedback": "社区与反馈",
    "Continuous": "连续",
    "Danger Zone": "危险区域",
    "Data Management": "数据管理",
    "Display active protocols on the right.": "在右侧显示当前生效协议",
    "Display exact millisecond attack cooldowns on Battle screen.": "在战斗界面显示精确到毫秒的攻击冷却",
    "Enables the developer dashboard in the header. (Hidden by default)": "在顶部栏启用开发者面板（默认隐藏）",
    "Hard Reset Game": "游戏硬重置",
    "Interface": "界面",
    "Keep the screen active while the game is open.": "游戏运行时保持屏幕常亮",
    "Manual Challenge Only": "仅手动挑战",
    "Never Switch (Only on Tab Click)": "绝不自动切换（仅点击标签切换）",
    "No dialog for Redraw animation.": "重绘动画不弹出对话框",
    "Prevent Screen Sleep": "防止屏幕休眠",
    "Show Protocol Sidebar": "显示协议侧边栏",
    "Skip Redraw Confirmation": "跳过重绘确认",
    "Sticky Notes": "便签",
    "Switch to Inverted Images": "切换为反色图像",
    "Switch to Normal Mode": "切换为浅色模式",
    "SYSTEM UNLOCK": "系统解锁",
    "This project is in very early development. I'm currently pushing 1-2 updates a day. Join our small tester community to track changes, suggest new features, and help refine the grind.": "本项目仍处于早期开发阶段，目前每日更新1～2次。加入我们的测试社区，可追踪更新、提出功能建议并协助优化玩法。",
    "View Last Redraw Summary": "查看上次重绘摘要",
    "Wipe your save and restart. irreversible.": "清除存档并重新开始，此操作不可撤销",
    "⚔️ Battle": "⚔️ 战斗",
    "Flee": "逃跑",
    "Min": "最小",
    "Cooldown:": "冷却时间:",
    "Victories": "胜利",
    "Victory": "胜利",
    "Attack Speed\nDelay between attacks in milliseconds. Lower is faster. Improved by SPD rewards (negative values).": "攻击速度\n每次攻击之间的间隔时间（以毫秒为单位）。数值越低，攻击速度越快。通过“敏捷度”奖励会有所提升（负值情况）。",
    "Shop": "商店",
    "A lazy \"M\" shape.": "一个慵懒的“M”形。",
    "Ink Drying...": "墨迹干了...",
    "seconds": "秒",
    "Path to Victory": "胜利之路",
    "Auto-Challenge is affordable!": "自动挑战费用低廉！",
    "He found a triangle.": "他发现了一个三角形。",
    "Shift Your Perspective": "转换你的视角",
    "Sometimes challenging enemies out of order can help you progress. Try a different path!": "有时打乱顺序挑战敌人有助于推进。试试另一条路线！",
    "Glossary Multiplier": "词条乘数",
    "Controls how fast rewards decay per victory. Reward for kill n = base / (1 + n × decay). Lower values mean slower decay and more total rewards.": "控制每次胜利时奖励的衰减速度。击杀奖励 n 的值为：基础值 / (1 + n × 衰减率)。衰减率越低，奖励的衰减速度就越慢，但总奖励值会更高。",
    "Total multiplier to ATK and HP gained from conquering unique sketches. Higher rarity sketches provide larger bonuses.": "通过攻克独特的草图所获得的攻击力和生命值的总加成值。越稀有的草图所提供的加成值越大。",
    "Wait time after defeat.": "失败后的等待时间。",
    "Wait time after fleeing.": "逃跑后的等待时间。",
    "○ Disabled": "○ 已禁用",
    "Buy": "购买",
    "Coffee": "咖啡",
    "LVL": "等级",
    "Ink": "墨水",
    "Market": "市场",
    "Tools": "工具",
    "The Shop": "商店",
    "The Market": "市场",
    "Unlock": "解锁",
    "UNLOCKED": "已解锁",
    "Upgrades": "升级",
    "Attack Speed": "攻击速度",
    "Attack Damage": "攻击伤害",
    "Auto-Challenge": "自动挑战",
    "Auto-Retry": "自动重试",
    "Stat Upgrades": "属性升级",
    "Aaigrsl Yllrewr Fetrde": "艾格斯尔·伊尔重写了费德",
    "Acrylic": "丙烯酸",
    "Active Protocols": "主动协议",
    "Adlhsbbla Ciayud": "Adlhsbbla Ciayud",
    "Aeronevc Brutitu": "勃鲁蒂托",
    "Affordable Only": "仅价格合理",
    "After losing battle, automatically challenge same opponent when cooldown finishes.": "输掉战斗后，冷却结束后自动挑战同一对手。",
    "Agr Ekiotnenr": "艾格·埃基翁纳",
    "Aretneim Itoc": "阿雷特奈姆·伊托克",
    "Armor\nFlat damage subtracted from every incoming hit after all other calculations. Reduced by the attacker's Armor Penetration.": "护甲\n经过所有其他计算后，从每次命中中减去平面伤害。因攻击者的护甲穿透力而减少。",
    "Automatically fight the same enemy for as long as you can survive.": "只要你能活下来，就会自动与同一个敌人作战。",
    "Automatically produces 0.01% of Charcoal you have gotten from Battle Rewards per second.": "每秒自动生成您从战斗奖励中获得的木炭的0.01%。",
    "Axc Tagwnoi": "Axc Tagwnoi",
    "Axe Slwa": "Axe Slwa",
    "Baseline damage dealt per attack before multipliers, variance, and damage reduction.": "在乘数、方差和伤害降低之前，每次攻击造成的基线伤害。",
    "Bftere Trtasieatt": "特塔西亚特先生",
    "Bold Lines": "粗线",
    "Bsent Dgeru": "Bsent Dgeru",
    "Cceeayn Olrtgrair": "塞恩·奥尔特格雷尔",
    "Charcoal": "木炭",
    "Charcoal Generator": "木炭发电机",
    "Clean Slate": "电脑保护软件",
    "Delay between attacks in milliseconds. Lower is faster. Improved by SPD rewards (negative values).": "攻击之间的延迟（毫秒）。越低越快。通过SPD奖励（负值）进行改进。",
    "Desrraed Geet": "放荡不羁的鹅",
    "Ditkhi Ncgseh": "Ditkhi Nggseh",
    "Dpese Ghsra": "Dpese Ghsra",
    "Eierrcs Rpeesa": "Eierrcs Rpeesa",
    "Entdyd Asha": "恩蒂德·阿莎",
    "Ereactce Lrddi": "Ereacce Lrddi",
    "Eslgnsi Uddem": "Eslgnsi Uddem",
    "Etuhipmp Rgpa": "Rgpa",
    "Feraepii Fncd": "Feraepii Fncd",
    "Fiaoe Cthsunl": "Fiaoe Cthsunl",
    "Gimcx Iotpnte": "Gimcx Iotpnte",
    "Gpreoycp Eifdrant": "Gpreoycp Eifdrant",
    "Gtudcrei Shoin Tapsrpue": "Gtudcrei Shoin Tapsrpue",
    "Hide Purchased": "隐藏已购买",
    "Hirotoc'r Cueasc": "Hirotoc’r Cueasc",
    "If auto-challenge reaches Max Victories, automatically move on to the first not maxed, non-hidden sketch.": "如果自动挑战达到最大胜利，则自动继续进行到第一个未达到最大、未隐藏的草图。",
    "Infinitely scaling upgrades for your battle stats. Focus on these to push past tougher enemies. Leveling them may require some clicking but you will soon automate them!": "无限扩展您的战斗统计数据升级。专注于这些，以击败更强硬的敌人。调整它们可能需要一些点击，但你很快就会自动完成它们！",
    "Inoadzrmer": "Inoadzrmer",
    "Isekudrall Tcac": "Isekudrall Tcac",
    "Itpeoiac Vetvr": "Itpeoac兽医",
    "Lbok Drreu": "Lbok Drreu",
    "Les Rldpi": "Les Rldpi",
    "Lonacuc Iiystdcr": "Lonacuc系统",
    "Lorem ipsum dolor sit amet...": "Lorem ipsum dolor坐着。..",
    "Marker": "标记",
    "Masuki Erncdrot": "Masuki Erncdrot",
    "Niadnest Rgord": "Niadnest Rgord",
    "No active protocols available.": "没有可用的活动协议。",
    "Noyip Asstucrd": "诺伊普·阿斯图克德",
    "Nte Nrinhki": "Nte Nrinhki",
    "Oam-Btarit Ietpldetne": "Oam Btarit",
    "Oaofne Trrfceeeg": "Oaofne Trrfceeeg",
    "Ocatos Rlnmrte": "Ocatos Rlnmrte",
    "Occeenr Inipstlsi": "事件发生",
    "Oduplieecn Rbacgt": "奥杜皮琴·鲁巴格特",
    "Onw xx Awa": "Onw xx Awa",
    "Oozgece Lndlzg": "Oozgece Lndlzg",
    "Pgrnho Enoatoter": "Pgrnho Enoatter",
    "Photon": "光子",
    "Pnary Resragteo": "肺炎球菌",
    "Portfolio Review": "作品集审查",
    "Protocols": "协议",
    "Protocols ☰": "协议☰",
    "Purchase special tools here. These are one-time unlocks that provide powerful capabilities like automation or passive income.": "在此处购买专用工具。这些是一次性解锁，提供自动化或被动收入等强大功能。",
    "Quick Strokes": "快速击球",
    "Rietav Wideu": "Rietav Wideu",
    "Rnrger Kaeemorta": "Rnrger Kaeemorta",
    "Sees Forrta": "看到Forrta",
    "Shpaxuop Etrerey": "Shpaxuop Etrerey",
    "Siido Llfl": "Siido Llfl",
    "Slnrcois Wrilog": "Slnrcois Wrilog",
    "Sockrrpwo Iein": "Sockrpwo Iein",
    "Soersdmcoe Rphaccal": "索尔斯德姆科·雷帕卡尔",
    "Spray": "喷雾",
    "Strguii'a Otrnsch": "Strguii'a Otrnsch",
    "Tdoiuo Iiqmnl": "蒂多约",
    "Tgpeirhe Getonraar": "Tgpeirhe Getonraar",
    "Thhni Kcdagis": "Thhni Kcdagis",
    "Thick Paper": "厚纸",
    "This is where you spend your all your currencies. The first one you will find is Graphite.": "这是你花掉所有货币的地方。你会发现的第一个是石墨。",
    "Tmciovia Ucrhp": "Tmciovia Ucrhp",
    "Unlock special tools from the market.": "从市场上解锁专用工具。",
    "Vyaotic Rpl": "Vyaotic Rpl",
    "When defeating an enemy, 20% chance to lose 20% of buffs and 20% of debuffs.": "击败敌人时，有20%的几率损失20%的增益和20%的减值。",
    "Wnx Argearteo": "Wnx Argarteo",
    "Note: Muted upgrades are also hidden when 'Affordable Only' is checked.": "注意：当“仅限经济型”选项被勾选时，低调升级也会被隐藏。",
    "Notifications Active": "通知已激活",
    "Some unlocked tools appear here as toggleable protocols, in addition to an expandable right-side panel (if your screen size allows). Be sure to toggle them in a way that helps optimize your progress!": "这里有一些未锁定的工具以可切换的协议形式呈现，此外还有一个可扩展的右侧面板（如果您的屏幕尺寸允许的话）。请务必以有助于优化您的进度的方式进行切换操作！",
    "This upgrade will trigger shop notifications.": "此次升级将会触发商店通知。",
    "● Active": "● 已激活",
    "Switch to Dark Mode": "切换到深色模式",
    "Switch to Original Images": "切换到原始图像",
    "Maximum health. Combat ends immediately when current health reaches zero.": "最大生命值。当当前生命值降为零时，战斗将立即结束。",
    "Hit Points": "生命值",
    "Your first milestone will come at 1618 total Graphite gained. This will turn on the Graphite Concept production which generates Quintessence. Each milestone after that will increase production per count by 1000x!": "您的第一个里程碑将在总获得 1618 个石墨时达成。届时将开启石墨概念生产模式，从而产生奇点物质。此后每个里程碑都会使每次的产量增加 1000 倍！",
    "You Died": "你挂了",
    " World": "世界",
    "/s": "/秒",
    "• Lv.": "• 等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "BRD": "BRD",
    "BRN": "BRN",
    "BNN": "BNN",
    "BLD": "BLD",
    "BLK": "BLK",
    "APN": "APN",
    "ACR": "ACR",
    "ACC": "ACC",
    "ABS": "ABS",
    "RGN": "RGN",
    "RMD": "RMD",
    "SPR": "SPR",
    "SLW": "SLW",
    "LFS": "LFS",
    "LEP": "LEP",
    "PLG": "PLG",
    "PRD": "PRD",
    "PRR": "PRR",
    "PSN": "PSN",
    "ARM": "护甲",
    "TIP": "提示",
    "LPT": "小贴士",
    "Graphite": "石墨",
    "GRA": "石墨",
    "MND": "最小伤害",
    "MXD": "最大伤害",
    "Stats": "属性",
    "SPD": "速度",
    "ATK": "攻击",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "−": "−",
    "∞": "∞",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "×": "×",
    "\"": "\"",
    "✕": "✕",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "VERSION - v": "版本 - v",
    "Stick Man": "火柴人",
    "Perspective Block": "视角阻挡",
    "Redraw": "重绘",
    "Smudge": "涂抹",
    "V-Wing Bat": "V翼蝙蝠",
    "Stick Knight": "火柴骑士",
    "New Glossary Entry: ": "新词条解锁：",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    ' (Default)': ' (默认)',
    " [Slow]": " [慢]",
    " [Fast]": " [快]",
    " [Fastest]": " [最快]",
    " [Slowest]": " [最慢]",
    " [Normal]": " [正常]",
    " (*)": " (*)",
    " (Prestige)": " (声望)",
    " (+)": " (+)",
    "Rotate your wrists. Draw the alphabet with your nose to relax your neck.": "转动你的手腕。用鼻子画出字母来放松你的颈部。",
    "Comparison is the thief of joy. Also, your stats are low.": "比较是偷走快乐的贼。另外，你的属性很低。",
    "Armor Penetration reduces the enemy's effective Armor value.": "护甲穿透力会降低敌人的有效护甲值。",
    "Wash your bedsheets. It's been too long.": "洗一下你的床单吧。已经很久没洗了。",
    "Congratulations, you made a number go up. Your ancestors hunting mammoths are proud.": "恭喜你，让数值上升了。你的祖先们猎杀猛犸象的日子又回来了，他们一定会感到自豪的。",
    "Sloths can hold their breath longer than dolphins can (up to 40 minutes).": "树懒能够屏住呼吸的时间比海豚要长得多（最长可达 40 分钟）。",
    "Statuses like Poison are effective against tanky sketches.": "像“毒液”这样的状态能够有效对付防御力强的怪兽。",
    "Don't let Quintessence Softcap intimidate you, sometimes you can push into double digit softcap exponents with ease.": "不要被“精髓”战队的上限限制所吓倒，有时候你完全可以轻松突破两位数的上限指数。",
    "This tip exists to fill an empty window. Just like your weekends.": "这个小窍门的作用就是填补空闲的时间。就像你的周末一样。",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.": "由于热胀冷缩的原因，埃菲尔铁塔在夏季可能会高出 15 厘米。",
    "Unclench your jaw. Drop your shoulders. Take a deep breath. You're welcome.": "放松你的下巴。放低你的肩膀。深吸一口气。不客气。",
    "Octopuses have three hearts. Two pump blood to the gills, one to the rest of the body.": "章鱼有三颗心脏。其中两颗心脏负责将血液泵送到鳃部，另一颗则负责为身体的其他部位输送血液。",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.": "我对妻子说她的眉毛画得太高了。她显得很惊讶。",
    "Staring at a screen for too long is bad for your eyes.": "长时间盯着屏幕看对眼睛不好。",
    "'Idle' is a game genre. It is also an accurate description of your ambition.": "‘放置’是一款游戏类型。它也恰如其分地描述了你的志向。",
    "Top left icon on each sketch on Gallery page can hide sketches that are of no use to you.": "在“相册”页面上的每个草图的左上角都有一个图标，通过点击该图标可以隐藏那些对你没有用处的草图。",
    "Change your passwords. 'Password123' is not a security measure.": "更改您的密码。“Password123”并非有效的安全设置。",
    "And the Lord said to John, 'Come forth and you shall receive eternal life.' But John came fifth and won a toaster.": "主对约翰说：“你出来吧，你将获得永生。”但约翰排在第五位，却赢得了一个烤面包机。",
    "The word 'pencil' comes from the Latin 'penicillus', meaning 'little tail'.": "“铅笔”这个词源于拉丁语“penicillus”，其含义为“小尾巴”。",
    "I'm sure your boss believes you're working on that spreadsheet right now.": "我敢肯定你的老板相信你现在正在处理那份电子表格呢。",
    "Botanically speaking, bananas are berries. Strawberries are not.": "从植物学的角度来看，香蕉属于浆果类，而草莓则不属于。",
    "Why don’t sculptors make good friends? They take everything for granite.": "为什么雕塑家们都不交朋友呢？因为他们对待一切事物都如同对待花岗岩一般冷漠无情。",
    "Why did the artist carry a pencil? In case he had to draw a weapon.": "为什么这位艺术家会随身携带一支铅笔呢？以防万一他需要画出一把武器来。",
    "You have killed 500 sketches. They had families. Probably stick families.": "你已经毁掉了 500 个草图。这些草图的作者都有家人，而且很可能都是有孩子的家庭。",
    "Export your save file occasionally. Cloud saves are great, but local backups are forever.": "定期将您的保存文件导出。云端保存固然不错，但本地备份则是永久性的。",
    "Remember to drink water.": "记得要喝水。",
    "I hope you're not playing this at work. Or do. I'm not HR.": "我希望你别在工作时这么做。或者就这么做吧。我可不是人力资源部门的人员。",
    "What did the 0 say to the 8? 'Nice belt.'": "零对8说了什么？“你的腰带真好看。”",
    "You are just changing 0s to 1s in a JSON file. Thrilling gameplay.": "你只是在 JSON 文件中把 0 改成 1 而已。游戏体验太棒了。",
    "Don't turn your brightness down. You might see your own reflection, and nobody wants that.": "不要调低你的亮度。你可能会看到自己的影像，而没人希望看到这种情况。",
    "Redrawing preserves your Glossary progress, making future runs easier.": "重新绘制会保留您的词汇表进度，从而让后续操作更加便捷。",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.": "平行线何其相似，却永远无法相交，真是可惜。",
    "Why did the artist go to jail? He was framed.": "艺术家为什么进监狱？因为他被人构陷了。（双关：被装裱了）",
    "I told a joke about a blank piece of paper. It was tearable.": "我讲了个关于空白纸张的笑话，烂得让人想哭。（双关：tearable = terrible / 可撕的）",
    "What is an artist’s favorite brand of shoe? Sketchers.": "艺术家最喜欢的鞋子品牌是什么？斯凯奇。（双关：Sketchers = sketch 素描）",
    "I tried to paint the sky, but I blue it.": "我试着画天空，结果搞砸了。（双关：blue = blew）",
    "What's brown and sticky? A stick.": "什么东西棕色的、黏糊糊的？一根棍子。",
    "Why don't skeletons fight each other? They don't have the guts.": "骷髅为什么不互相打架？因为它们没胆子。（双关：没内脏）",
    "Sketching is just taking a line for a walk.": "素描不过就是带着一根线条散散步。",
    "Shout out to people who don't know what the opposite of 'in' is.": "致敬那些不知道“in”反义词是什么的人。",
    "Turn on 'Night Light' or 'Eye Comfort' mode on your device after sunset.": "日落后请打开设备的“夜览”或“护眼模式”。",
    "Vitamin D supplements are crucial if you spend all day indoors gaming.": "如果你整天宅在屋里打游戏，补充维生素D非常重要。",
    "Cooking a meal takes 30 minutes. Ordering delivery takes 45. Save money, cook food.": "做饭只要30分钟，点外卖要45分钟。省钱，自己做饭吧。",
    "Call your parents. They probably miss you more than you miss this game.": "给父母打个电话。他们想你，多半比你想这款游戏更甚。",
    "Listen to a podcast while grinding. It makes you feel productive by association.": "刷本的时候听听播客，会让你莫名觉得自己很高效。",
    "If you have to ask 'is it too late to go to bed?', the answer is always yes.": "如果你还在问“现在睡觉是不是太晚了”，答案永远是：是的。",
    "Open a window. The air in your room is mostly carbon dioxide and regret.": "打开一扇窗。你房间里的空气，大半是二氧化碳和后悔。",
    "Don't hoard Quintessence too long; investing early compounds your power faster.": "别囤着精华太久；越早投资，你的实力复利增长越快。",
    "The Quintessence icon in the top right corner is a shortcut to the Conceptual Synthesizer.": "右上角的精华图标是通往概念合成器的快捷方式。",
    "Stuck on a sketch? Try killing the one after it first.": "卡在某张素描过不去？先去干掉它后面的那个试试。",
    "Crit Damage is useless without Crit Chance. Balance your stats wisely.": "没有暴击率，暴击伤害就是摆设。合理平衡你的属性。",
    "You can review the Tutorial anytime in Settings.": "你可以随时在设置里回顾教程。",
    "Stacking Freeze above 100% turns enemy healing into damage.": "冻结效果堆到100%以上，会把敌人的治疗转化为伤害。",
    "Increasing Speed reduces the cooldown between your attacks.": "提升速度会减少你的攻击间隔冷却。",
    "100% of sketches in this game are actually digital.": "这款游戏里所有的素描，其实全是数字绘制的。",
    "The average person spends 6 months of their life waiting for red lights to turn green.": "普通人一生中平均要花6个月时间等红灯变绿。",
    "Yellow pencils became standard in the 1890s to signify Chinese graphite quality.": "黄色铅笔在1890年代成为标配，用以代表优质中国石墨。",
    "Before rubber erasers, people used balled-up white bread to remove graphite marks.": "在橡胶橡皮擦出现之前，人们用揉成团的白面包擦掉石墨痕迹。",
    "Hemingway used to sharpen his pencils with a knife. It made him feel more like a hunter.": "海明威过去常用小刀削铅笔，这让他觉得自己更像个猎人。",
    "Graphite is a conductor of electricity. Do not stick pencils in outlets.": "石墨可以导电。别把铅笔插进插座里。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^\-([\d\.]+) \/ ([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+)Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\~([\d\.,]+) WPM$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)ms$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\*([\d\.]+) SPD per level$/, '每级 *$1 速度'],
    [/^\+([\d\.]+)\% HP per level$/, '每级 +$1% 生命值'],
    [/^\+([\d\.]+)\% ATK per level$/, '每级 +$1% 攻击'],
    [/^\+([\d\.]+)\% Rough rarity chance$/, '+$1% 粗糙稀有度几率'],
    [/^([\d\.]+)\% multiplier$/, '$1% 乘数'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^LPT \#([\d\.,]+): $/, '小贴士 #$1: '],
    [/^FACT \#([\d\.,]+): $/, '事实 #$1: '],
    [/^JOKE \#([\d\.,]+): $/, '笑话 #$1: '],
    [/^CRITIQUE \#([\d\.,]+): $/, '评论 #$1: '],
    [/^TIP \#([\d\.,]+): $/, '提示 #$1: '],
    [/^Every ([\d\.,]+)s$/, '每 $1 秒'],
    [/^Every ([\d\.,]+)m$/, '每 $1 分钟'],
    [/^Magnum Opus ([\d\.,]+)$/, '杰作 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^ defeated! \nRewards:\n\+(.+) HP\n\+(.+) Graphite$/, ' 已击败! \n奖励:\n+$1 生命值\n+$2 石墨'],
    [/^ defeated! \nRewards:\n\+(.+) ATK\n\+(.+) Graphite$/, ' 已击败! \n奖励:\n+$1 攻击\n+$2 石墨'],
    [/^ defeated! \nRewards:\n\+(.+) ATK\n\+(.+) SPD\n\+(.+) Graphite$/, ' 已击败! \n奖励:\n+$1 攻击\n+$2 速度\n+$3 石墨'],
    [/^ defeated! \nRewards:\n\+(.+) ATK\n\+(.+) ARM\n\+(.+) Graphite$/, ' 已击败! \n奖励:\n+$1 攻击\n+$2 护甲\n+$3 石墨'],
    [/^ defeated! \nRewards:\n\+(.+) HP\n\+(.+) ATK\n\+(.+) Graphite$/, ' 已击败! \n奖励:\n+$1 生命值\n+$2 攻击\n+$3 石墨'],
    [/^Defeated by (.+)! 10 second cooldown.$/, '你被 $1 击败了！冷却 10 秒。'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);